// Cloudflare Workers global types. Generated by hand to match wrangler.toml
// bindings — run `wrangler types` later if you prefer auto-generation.

declare global {
  interface Env {
    /** D1 binding — primary storage for wishes, postcards, etc. */
    DB: D1Database;
    /** R2 binding — large apple-photo image / video blobs (>1 MB). */
    PHOTOS: R2Bucket;
    /** Workers Static Assets — Vite build output. */
    STATIC: { get: (path: string) => Promise<Response | null> };
    /** App-level public identifier. */
    APP_ID: string;
    /** Admin token required by `x-admin-token` header on /api/trpc/admin.* */
    ADMIN_TOKEN: string;
    /** Reserved for internal server-to-server calls. */
    APP_SECRET: string;
  }
}

export {};
